### ISSUE TITLE
undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'

### ISSUE THREAD

**Issue by samuelyenyen** [ultraembedded/biriscv#22]
I have this error when running makefile in tb/tb_top.
May I ask what version of verilator do you use?
I use v5.012

./lib/libsyscverilated.a: undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
collect2: error: ld returned 1 exit status
make[1]: *** [build/test.x] Error 1
make[1]: Leaving directory `/disk2/others/dsd_311591023/try/biriscv/tb/tb_top'
make: *** [build] Error 2

**Comment by SB308** [comment]
Compiles on Verilator 4.028 shipped with Ubuntu 20.04

**Comment by vibarajanv** [comment]
I tried 4.028 version. I get a different error that "verilog.h file is not available in the repo"

**Comment by vibarajanv** [comment]
I tried 5.030 and 4.038 
They both have the error: VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)' collect2: error: ld returned 1 exit status make[1]: *** [build/test.x] Error 1 make[1]: Leaving directory 

I believe 5.030 is stable version. 

I did the following: 

git checkout stable
git pull
